export const FETCH_COLLECTIONS = 'COLLECTIONS/FETCH_COLLECTIONS';
export const FETCH_COLLECTIONS_SUCCESS = 'COLLECTIONS/FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_ERROR = 'COLLECTIONS/FETCH_COLLECTIONS_ERROR';

export const SET_FILTER_SEARCH = 'COLLECTIONS/SET_COLLECTIONS_SEARCH';
export const CREATE_COLLECTION = 'COLLECTIONS/CREATE_COLLECTION';
export const CREATE_COLLECTION_SUCCESS = 'COLLECTIONS/CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_ERROR = 'COLLECTIONS/CREATE_COLLECTION_ERROR';
export const FETCH_COLLECTION = 'COLLECTIONS/FETCH_COLLECTION';
export const FETCH_COLLECTION_SUCCESS = 'COLLECTIONS/FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_ERROR = 'COLLECTIONS/FETCH_COLLECTION_ERROR';

export const DELETE_COLLECTION = 'COLLECTIONS/DELETE_COLLECTION';
export const DELETE_COLLECTION_SUCCESS = 'COLLECTIONS/DELETE_COLLECTION_SUCCESS';
export const DELETE_COLLECTION_ERROR = 'COLLECTIONS/DELETE_COLLECTION_ERROR';

export const UPDATE_COLLECTION = 'COLLECTIONS/UPDATE_COLLECTION';
export const UPDATE_COLLECTION_SUCCESS = 'COLLECTIONS/UPDATE_COLLECTION_SUCCESS';
export const UPDATE_COLLECTION_ERROR = 'COLLECTIONS/UPDATE_COLLECTION_ERROR';
export const UPDATE_COLLECTION_STATISTICS = 'COLLECTIONS/UPDATE_COLLECTION_STATISTICS';

export const UPDATE_COLLECTION_BIMOBJECTS = 'COLLECTIONS/UPDATE_COLLECTION_BIMOBJECTS';
export const UPDATE_COLLECTION_BIMOBJECTS_SUCCESS =
  'COLLECTIONS/UPDATE_COLLECTION_BIMOBJECTS_SUCCESS';
export const UPDATE_COLLECTION_BIMOBJECTS_ERROR = 'COLLECTIONS/UPDATE_COLLECTION_BIMOBJECTS_ERROR';

export enum CollectionStatus {
  Deleted = 'deleted',
  Private = 'private',
  Shared = 'shared',
  Public = 'public',
}