export default {
  Search: {
    SortByCreatedAtOption: 'Created at',
    SortByLastUpdateOption: 'Last update',
    SortByNameOption: 'Alphabetically',
    SortBySizeOption: 'Size',
    SortByRelevance: 'Relevance',
    SortAscending: 'Ascending',
    SortDescending: 'Descending',
  },
  Filters: {
    CounterLabel: 'contents',
    SubmitFilters: 'Submit',
    SoftwaresLabel: 'Software',
    SoftwaresPlaceholder: 'Filter by software...',
    UboKindsLabel: 'UBO kinds',
    UboKindsPlaceholder: 'Filter by UBO kind...',
    ContentTypeLabel: 'Content type',
    ContentTypePlaceholder: 'Filter by content type...',
    LodsLabel: 'LOD',
    ClassificationsLabel: 'Classifications',
    LodsPlaceholder: 'Filter by LOD...',
    TagsLabel: 'tags',
    TagsPlaceholder: 'Filter by tag...',
    ClassificationsPlaceholder: 'Filter by classification...',
    ParametersLabel: 'Parameters',
  },
  SearchResults: {
    NoOptions: 'No options',
    Loading: 'Loading...',
  },
  Inspector: {
    CreatedAtLabel: 'Creation',
    UpdatedAtLabel: 'Last Update',
    DownloadButton: 'Download',
    PreviewButton: 'Preview',
    SeeMoreButton: 'See more',
    SeeLessButton: 'See less',
    ObjectTitle: 'Relative to object',
    ClassificationsTitle: 'Classifications',
    PinsTitle: 'Pins',
    ParametersTitle: 'Parameters',
  },
  Preview: {
    VariantsFilterPlaceholder: 'Variants',
    PreviewVariantsDefaultOption: 'Thumbnail',
  },
};
