import { Property } from '../../../../Reducers/Sets/Properties/types';
import { Subset } from '../../../../Reducers/Sets/Subsets/types';

export const UPDATE_SUBSET = 'PROPERTIES_PICKER/UPDATE_SUBSET';
export const UPDATE_PROPERTIES = 'PROPERTIES_PICKER/UPDATE_PROPERTIES';
export const SELECT_SUBSET = 'PROPERTIES_PICKER/SELECT_SUBSET';
export const SELECT_PROPERTY = 'PROPERTIES_PICKER/SELECT_PROPERTY';
export const SELECT_ALL_SUBSETS = 'PROPERTIES_PICKER/SELECT_ALL_SUBSETS';
export const SELECT_ALL_PROPERTIES = 'PROPERTIES_PICKER/SELECT_ALL_PROPERTIES';
export const UNSELECT_ALL_SUBSETS = 'PROPERTIES_PICKER/UNSELECT_ALL_SUBSETS';
export const UNSELECT_ALL_PROPERTIES = 'PROPERTIES_PICKER/UNSELECT_ALL_PROPERTIES';
export const REMOVE_SELECTED_SUBSET = 'PROPERTIES_PICKER/REMOVE_SELECTED_SUBSET';
export const REMOVE_SELECTED_PROPERTY = 'PROPERTIES_PICKER/REMOVE_SELECTED_PROPERTY';
export const CHANGE_CURRENT_DISPLAY_TYPE = 'PROPERTIES_PICKER/CHANGE_CURRENT_DISPLAY_TYPE';
export const UNSELECT_ALL = 'PROPERTIES_PICKER/UNSELECT_ALL';

/**
 * Models
 */

export type ExistingElements = {
  properties?: Property[];
  subsets?: Subset[];
};

/**
 * Actions
 */

export type UnSelectAllAction = {
  type: typeof UNSELECT_ALL;
};