const ENVIRONMENTS = {
  dev: {
    API_URL: 'https://dev.bimandco.com',
    SSO_URL: 'https://preprodauth.bimandco.com',
    METABASE_SITE_URL: 'https://metabase.bimandco.com',
    ONLINE_HELP_URL: 'https://faq.onfly.io',
    ONFLY_HTTP_PROTOCOL: 'https',
    ONFLY_DOMAIN: '.dev.onfly.io:3000',
    ADOBE_PDF_VIEWER_CLIENT_ID: '2a1d4d7be6ca49a0b82a41b5e521f853',
    ADOBE_PDF_VIEWER_URL: 'https://bimandco.dev.onfly.io:3000',
  },
  test: {
    API_URL: 'https://test.bimandco.com',
    SSO_URL: 'https://testauth.bimandco.com',
    METABASE_SITE_URL: 'https://metabase.bimandco.com',
    ONLINE_HELP_URL: 'https://faq.onfly.io',
    ONFLY_HTTP_PROTOCOL: 'http',
    ONFLY_DOMAIN: '.test.onfly.io',
    ADOBE_PDF_VIEWER_CLIENT_ID: 'b253f9e3d524468d8d02b09ef1fc5e11',
    ADOBE_PDF_VIEWER_URL: 'https://bimandco.test.onfly.io',
  },
  preprod: {
    API_URL: 'https://preprod.bimandco.com',
    SSO_URL: 'https://preprodauth.bimandco.com',
    METABASE_SITE_URL: 'https://metabase.bimandco.com',
    ONLINE_HELP_URL: 'https://faq.onfly.io',
    ONFLY_HTTP_PROTOCOL: 'https',
    ONFLY_DOMAIN: '.preprod.onfly.io',
    ADOBE_PDF_VIEWER_CLIENT_ID: '088c8ccdd2fc4db9a1cc9c04969b3d93',
    ADOBE_PDF_VIEWER_URL: 'https://bimandco.preprod.onfly.io',
  },
  prod: {
    API_URL: 'https://www.bimandco.com',
    SSO_URL: 'https://auth.bimandco.com',
    IS_PROD: true,
    METABASE_SITE_URL: 'https://metabase.bimandco.com',
    ONLINE_HELP_URL: 'https://faq.onfly.io',
    ONFLY_HTTP_PROTOCOL: 'https',
    ONFLY_DOMAIN: '.onfly.io',
    ADOBE_PDF_VIEWER_CLIENT_ID: 'a154dc591bd8471d9c44100f008525aa',
    ADOBE_PDF_VIEWER_URL: 'https://bimandco.onfly.io',
  },
  prodrc: {
    API_URL: 'https://www-rc.bimandco.com',
    SSO_URL: 'https://auth-rc.bimandco.com',
    IS_PROD: true,
    METABASE_SITE_URL: 'https://metabase-rc.bimandco.com',
    ONLINE_HELP_URL: 'https://faq.onfly.io',
    ONFLY_HTTP_PROTOCOL: 'https',
    ONFLY_DOMAIN: '.rc.onfly.io',
    ADOBE_PDF_VIEWER_CLIENT_ID: 'fd77154ec4bc490cb0bc7d9837ff8e60',
    ADOBE_PDF_VIEWER_URL: 'https://bimandco-rc.onfly.io',
  },
};

module.exports = ENVIRONMENTS;
