// groups
export const GET_CLASSIFICATIONS_LIST = 'GET_CLASSIFICATIONS_LIST';
export const UPDATE_CLASSIFICATIONS_LIST = 'UPDATE_CLASSIFICATIONS_LIST';
export const GET_CLASSIFICATION_NODES = 'GET_CLASSIFICATION_NODES';
export const UPDATE_CLASSIFICATION_NODES = 'UPDATE_CLASSIFICATION_NODES';
