// Users
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const LOAD_MORE = 'LOAD_MORE';
export const SELECT_BIMOBJECT = 'SELECT_BIMOBJECT';
export const REFRESH_REQUEST = 'REFRESH_REQUEST';
export const SAVE_SCROLL_POSITION = 'SAVE_SCROLL_POSITION';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const OPEN_OBJECT_CARD = 'OPEN_OBJECT_CARD';
export const DELETE_OBJECTS_FROM_RESULTS = 'DELETE_OBJECTS_FROM_RESULTS';
