export const OCMappedResources = (resources, OCResources) => ({
  ...OCResources,
  MetaResource: {
    Cancel: resources?.MetaResource?.Cancel,
  },
  Search: {
    SearchPlaceholder: resources?.SearchResults?.FilterPlaceholder,
  },
  ContentManager: {
    ObjectCouldNotPublished: resources?.ContentManager?.ObjectCouldNotPublished,
    ObjectsCouldNotPublished: resources?.ContentManager?.ObjectsCouldNotPublished,
    SomeObjectsCouldNotPublished: resources?.ContentManager?.SomeObjectsCouldNotPublished,
    UpdateObjectStatusFailed: resources?.ContentManager?.UpdateObjectStatusFailed,
    ResultsPerPage: resources?.ContentManager?.ResultsPerPage,
    ResultsCount: resources?.ContentManager?.ResultsCount,
    FilterContains: resources?.ContentManager?.FilterContains,
    FilterNotContain: resources?.ContentManager?.FilterNotContain,
    FilterReset: resources?.ContentManager?.FilterReset,
    FilterResetAll: resources?.ContentManager?.FilterResetAll,
    FilterInList: resources?.ContentManager?.FilterInList,
    FilterNotInList: resources?.ContentManager?.FilterNotInList,
    FilterEmpty: resources?.ContentManager?.FilterEmpty,
    FilterNotEmpty: resources?.ContentManager?.FilterNotEmpty,
    CreateObject: resources?.ContentManager?.CreateObject,
    MenuEditOption: resources?.ContentManager?.MenuEditOption,
    MenuDuplicateOption: resources?.ContentManager?.MenuDuplicateOption,
    MenuDuplicateLibraryOption: resources?.ContentManager?.MenuDuplicateLibraryOption,
    MenuDeleteOption: resources?.ContentManager?.MenuDeleteOption,
    MenuFilterResetOption: resources?.ContentManager?.MenuFilterResetOption,
    MenuFilterResetAllOption: resources?.ContentManager?.MenuFilterResetAllOption,
    MenuFilterContainsOption: resources?.ContentManager?.MenuFilterContainsOption,
    MenuFilterNotContainsOption: resources?.ContentManager?.MenuFilterNotContainsOption,
    AddToSpace: resources?.ContentManager?.AddToSpace,
    AddToCollection: resources?.ContentManager?.AddToCollection,
    EditTags: resources?.ContentManager?.EditTags,
    EditClassifications: resources?.ContentManager?.EditClassifications,
    SelectedObjectsCount: resources?.ContentManager?.SelectedObjectsCount,
    EditOnflyStatus: resources?.ContentManager?.EditOnflyStatus,
    EditBimAndCoComStatus: resources?.ContentManager?.EditBimAndCoComStatus,
    EditWhiteLabelSiteStatus: resources?.ContentManager?.EditWhiteLabelSiteStatus,
    Delete: resources?.ContentManager?.Delete,
    NotPublished: resources?.ContentManager?.NotPublished,
    Published: resources?.ContentManager?.Published,
    Deleted: resources?.ContentManager?.Deleted,
    Absent: resources?.ContentManager?.Absent,
    MenuMapOption: resources?.ContentManager?.MenuMapOption,
    MapObjects: resources?.ContentManager?.MapObjects,
    MapObjectFailed: resources?.ContentManager?.MapObjectFailed,
    MapObjectsSuccess: resources?.ContentManager?.MapObjectsSuccess,
    Columns: {
      Name: resources?.ContentManager?.NameLabel,
      Spaces: resources?.ContentManager?.SpacesLabel,
      Collections: resources?.ContentManager?.CollectionsLabel,
      Tags: resources?.ContentManager?.TagsLabel,
      OnflyStatus: resources?.ContentManager?.OnflyStatusLabel,
      BimAndCoComStatus: resources?.ContentManager?.BimAndCoComStatusLabel,
      WhiteLabelSiteStatus: resources?.ContentManager?.WhiteLabelSiteStatusLabel,
      Manufacturer: resources?.ContentManager?.ManufacturerLabel,
      Author: resources?.ContentManager?.AuthorLabel,
      CreationDate: resources?.ContentManager?.CreationDateLabel,
      Updator: resources?.ContentManager?.UpdatorLabel,
      ModificationDate: resources?.ContentManager?.ModificationDateLabel,
      DropdownNoOptions: resources?.ContentManager?.ColumnsDropdownNoOptions,
      DropdownSearch: resources?.ContentManager?.ColumnsDropdownSearch,
    },
    WaitingForConfiguration: resources?.ContentManager?.WaitingForConfiguration,
    DeleteObjects: resources?.ContentManager?.DeleteObjects,
    DeleteObject: resources?.ContentManager?.DeleteObject,
    DeleteObjectsPopinTitle: resources?.ContentManager?.DeleteObjectsPopinTitle,
    DeleteObjectPopinTitle: resources?.ContentManager?.DeleteObjectPopinTitle,
    DeleteObjectsPopinConfirm: resources?.ContentManager?.DeleteObjectsPopinConfirm,
    DeleteObjectPopinConfirm: resources?.ContentManager?.DeleteObjectPopinConfirm,
    DuplicateBimObjectSuccess: resources?.ContentManager?.DuplicateBimObjectSuccess,
    DuplicateBimObjectError: resources?.ContentManager?.DuplicateBimObjectError,
    DuplicateBimObjectInProgress: resources?.ContentManager?.DuplicateBimObjectInProgress,
    DeleteObjectFailed: resources?.ContentManager?.DeleteObjectFailed,
    SpacesObjectsCopyDialog: {
      TitleInProgress: resources?.ContentManager?.SpacesObjectsCopyDialogTitleInProgress,
      TitleCompleted: resources?.ContentManager?.SpacesObjectsCopyDialogTitleCompleted,
      DescriptionInProgress:
        resources?.ContentManager?.SpacesObjectsCopyDialogDescriptionInProgress,
      DescriptionSuccess: resources?.ContentManager?.SpacesObjectsCopyDialogDescriptionSuccess,
      DescriptionError: resources?.ContentManager?.SpacesObjectsCopyDialogDescriptionError,
    },
  },
  Libraries: {
    LibrariesPlaceholder: resources?.SearchResults?.LibrariesPlaceholder,
    MyLibrary: resources?.ContentManagement?.MyLibrary,
    MyOnflyLibrary: resources?.ContentManagement?.MyOnflyLibrary,
    MyEntityLibrary: resources?.ContentManagement?.MyEntityLibrary,
    BimAndCoLibrary: resources?.ContentManagement?.BimAndCoLibrary,
    AllSpaces: resources?.ContentManagement?.AllSpaces,
  },
  ClassificationsModal: {
    NoResults: resources?.ClassificationsModal?.NoResults,
    SaveButton: resources?.ClassificationsModal?.SaveButton,
    SelectedClassifications: resources?.ClassificationsModal?.SelectedClassifications,
    TitleOneObject: resources?.ClassificationsModal?.TitleOneObject,
    TitleManyObjects: resources?.ClassificationsModal?.TitleManyObjects,
    SearchPlaceholder: resources?.ClassificationsModal?.SearchPlaceholder,
    DeleteModalTitle: resources?.ClassificationsModal?.DeleteModalTitle,
    DeleteModalDescription: resources?.ClassificationsModal?.DeleteModalDescription,
    DeleteModalCheckboxLabel: resources?.ClassificationsModal?.DeleteModalCheckboxLabel,
    DeleteModalDeleteButton: resources?.ClassificationsModal?.DeleteModalDeleteButton,
    ClassificationsDropdownNoOptions:
      resources?.ClassificationsModal?.ClassificationsDropdownNoOptions,
  },
  Filters: {
    CounterLabel: resources?.SearchResults?.SearchCount.replace('[Optional]', '').replace(
      '[Total]',
      ''
    ),
  },
});
