export default {
  ContentManager: {
    CreateObject: 'Object',
    MenuEditOption: 'Edit',
    MenuDuplicateOption: 'Duplicate',
    MenuDuplicateLibraryOption: 'Duplicate in my library',
    MenuDeleteOption: 'Delete',
    MenuFilterResetOption: 'Reset',
    MenuFilterResetAllOption: 'Reset All',
    MenuFilterContainsOption: 'Contains',
    MenuFilterNotContainsOption: 'Does not contain',
    AddToSpace: 'Add to a space',
    EditTags: 'Edit tags',
    EditClassifications: 'Edit classifications',
    SelectedObjectsCount: '[count] selected objects',
    EditBimAndCoComStatus: 'Edit BIM&CO status',
    EditWhiteLabelSiteStatus: 'Edit white label site status',
    Delete: 'Delete',
    NotPublished: 'Not published',
    Published: 'Published',
    Deleted: 'Deleted',
    Absent: 'Absent',
    Columns: {
      Name: 'Name',
      Spaces: 'Spaces',
      Tags: 'Tags',
      OnflyStatus: 'Onfly status',
      BimAndCoComStatus: 'BIM&CO status',
      WhiteLabelSiteStatus: 'White label site status',
      Author: 'Author',
      CreationDate: 'Date of creation',
      Updator: 'Modified by',
      ModificationDate: 'Date of modification',
    },
    WaitingForConfiguration: 'waiting for configuration...',
    DeleteObjects: 'Delete objects',
    DeleteObject: 'Delete object',
    DeleteObjectsPopinTitle: 'Delete [count] objects',
    DeleteObjectPopinTitle: 'Delete [object_name]',
    DeleteObjectsPopinConfirm:
      'Are you sur you want to delete these objects ? By Clicking on "Delete", they will be removed permanently from your Onfly library.',
    DeleteObjectPopinConfirm:
      'Are you sur you want to delete [object_name] ? By Clicking on "Delete", they will be removed permanently from your Onfly library.',
  },
};
