// todo: actions should be prefixed with APP/ to avoid collision
export const SET_LOADER = 'LOADER';
export const TOGGLE_EDIT_RESOURCES = 'TOGGLE_EDIT_RESOURCES';
export const LOGOUT = 'LOGOUT';
export const UPDATE_TEMPORARY_TOKEN = 'UPDATE_TEMPORARY_TOKEN';
export const RESET_AUTH_TOKEN = 'RESET_AUTH_TOKEN';
export const UPDATE_INFORMATIONS_CONTEXT = 'UPDATE_INFORMATIONS_CONTEXT';

export const SET_CRISP_METADATA = 'APP/SET_CRISP_METADATA';
export const LOG_ERROR = 'APP/LOG_ERROR';
export const SET_DOCUMENT_TITLE = 'APP/SET_DOCUMENT_TITLE';

export const FETCH_DOCUMENT_TYPES = 'APP/FETCH_DOCUMENT_TYPES';
export const FETCH_DOCUMENT_TYPES_SUCCESS = 'APP/FETCH_DOCUMENT_TYPES_SUCCESS';
export const FETCH_DOCUMENT_TYPES_ERROR = 'APP/FETCH_DOCUMENT_TYPES_ERROR';

export const FETCH_LANGUAGES = 'APP/FETCH_LANGUAGES';
export const FETCH_LANGUAGES_SUCCESS = 'APP/FETCH_LANGUAGES_SUCCESS';
export const FETCH_LANGUAGES_ERROR = 'APP/FETCH_LANGUAGES_ERROR';

export const SET_URL = 'URL';
