export const FETCH_SPACES = 'SPACES/FETCH_SPACES';
export const FETCH_SPACES_SUCCESS = 'SPACES/FETCH_SPACES_SUCCESS';
export const FETCH_SPACES_ERROR = 'SPACES/FETCH_SPACES_ERROR';
export const CREATE_SPACE = 'SPACES/CREATE_SPACE';
export const CREATE_SPACE_SUCCESS = 'SPACES/CREATE_SPACE_SUCCESS';
export const CREATE_SPACE_ERROR = 'SPACES/CREATE_SPACE_ERROR';

export const DELETE_SPACE = 'SPACE/DELETE_SPACE';
export const DELETE_SPACE_SUCCESS = 'SPACE/DELETE_SPACE_SUCCESS';
export const DELETE_SPACE_ERROR = 'SPACE/DELETE_SPACE_ERROR';

export const UPDATE_SPACE = 'SPACES/UPDATE_SPACE';
export const UPDATE_SPACE_SUCCESS = 'SPACES/UPDATE_SPACE_SUCCESS';
export const UPDATE_SPACE_ERROR = 'SPACES/UPDATE_SPACE_ERROR';

export const SET_FILTER_SEARCH = 'SPACE/SET_SPACE_SEARCH';
export const UPDATE_STATUS = 'SPACE/UPDATE_STATUS';

export const SET_SORT_ORDER_BY = 'SPACES/SET_SORT_ORDER_BY';
export const SET_SORT_DIRECTION = 'SPACES/SET_SORT_DIRECTION';

export const ASK_AUTHORIZATION = 'SPACES/ASK_AUTHORIZATION';
export const ASK_AUTHORIZATION_SUCCESS = 'SPACES/ASK_AUTHORIZATION_SUCCESS';
export const ASK_AUTHORIZATION_ERROR = 'SPACES/ASK_AUTHORIZATION_ERROR';

export enum SpacesStatus {
  InDeployement = 'inDeployement',
  Actif = 'actif',
  RequestAccessSend = 'requestAccessSend',
}

export const MAX_LENGTH_SUBDOMAIN = 63;
export const MAX_LENGTH_ENV_SUFFIX_SUBDOMAIN = 8; // "-preprod"