export const SET_PROPERTIES_SETS = 'PROPERTIES_SETS/SET_PROPERTIES_SETS';
export const SET_FILTER = 'PROPERTIES_SETS/SET_FILTER';
export const SET_API_STATE = 'PROPERTIES_SETS/SET_API_STATE';
export const SET_SORT_ORDER_BY = 'PROPERTIES_SETS/SET_SORT_ORDER_BY';
export const SET_SORT_DIRECTION = 'PROPERTIES_SETS/SET_SORT_DIRECTION';

export const FETCH_SET = 'PROPERTIES_SETS/FETCH_SET';
export const FETCH_SET_SUCCESS = 'PROPERTIES_SETS/FETCH_SUCCESS_SET';
export const FETCH_SET_ERROR = 'PROPERTIES_SETS/FETCH_ERROR_SET';

export const FETCH_SETS = 'PROPERTIES_SETS/FETCH_SETS';
export const FETCH_SETS_SUCCESS = 'PROPERTIES_SETS/FETCH_SETS_SUCCESS';
export const FETCH_SETS_ERROR = 'PROPERTIES_SETS/FETCH_SETS_ERROR';

export enum Nature {
  TYPE = 0,
  INSTANCE = 1,
}